version: "3"

services:
  python-flask:
    container_name: python-flask-container
    build:
      context: ./
      dockerfile: Dockerfile
    image: ravindu0823/musify:1.1.2
    environment:
      - PYTHON_ENV=PRODUCTION
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge